on:
  push:
   branches: ["main"]
  pull_request:
    branches: ["main"]
    
name: Continuous Integration

jobs:
  ci:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        toolchain:
          - stable
          # - nightly

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: thumbv7em-none-eabihf

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}-${{ matrix.toolchain }}

      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --examples -F defmt

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          target: thumbv7em-none-eabihf

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ubuntu-latest-stable

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --examples -F defmt
